#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Zhe Li <linuxcity.jn@gmail.com>
#
# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#-- My Settings ---
export EDITOR='/usr/local/bin/vim'
export MANPATH="/usr/local/man:$MANPATH"

# ignore command with space prefix in history
export HISTCONTROL=ignorespace

# vim 256 color
export TERM='xterm-256color'

# my local bin
PATH=$PATH:$HOME/.local/bin

# conscript
export CONSCRIPT_HOME="$HOME/.conscript"
export CONSCRIPT_OPTS="-XX:MaxPermSize=512M -Dfile.encoding=UTF-8"
export PATH=$CONSCRIPT_HOME/bin:$PATH

# fzf
FZF_TMUX=1

# GOLANG
export GOPATH="$HOME/.local/golang"
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$GOPATH/bin:$PATH"

# java
# Use current java version from java_home
export JAVA_HOME=$(/usr/libexec/java_home)
# Use JDK8
#export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH

# Ruby
## RVM
### Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# NodeJS
## NVM
export NVM_DIR="$HOME/.nvm"

# Scala
## SBT
export SBT_OPTS="-Xmx1024M -XX:+CMSClassUnloadingEnabled"

# SSH
export SSH_KEY_PATH="~/.ssh/rsa_id"

# zsh substring history search
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="bg=red,fg=white,bold"

# zsh-autosuggest
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=59"

# zsh cache for completion
export ZSH_CACHE_DIR="$HOME/.zsh/completion"

#-- End of My Settings ---
